server:
  port: 8080

spring:
  application:
    name: file-search-system

  datasource:
#    url: jdbc:postgresql://localhost:55432/postgres
#    url: jdbc:postgresql://172.21.20.51:55432/ocr
    url: jdbc:postgresql://172.21.0.219:55432/ocr
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  kafka:
    #bootstrap-servers: localhost:9092
    bootstrap-servers: 172.21.0.219:9092
    consumer:
      group-id: file-search-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

# 파일 스캔 경로 설정
file-scan:
  base-path: D:\\Dev2Team\\ocr_file\\ocr_test_file  #C:\\OCR\\testfile
  supported-extensions: .doc,.docx,.xls,.xlsx,.ppt,.pptx,.pdf,.txt,.png,.jpg,.jpeg

# OpenSearch 설정
opensearch:
#  host: localhost
  host: 172.21.0.219
  port: 9200
  scheme: https
  username: admin
  password: OpenSearch#2026!
  index-name: file-contents

# PaddleOCR 설정 (Python REST API 서비스)
paddle-ocr:
#  api-url: http://localhost:45678/ocr
  api-url: http://172.21.0.219:45678/ocr
  enabled: true

# Kafka 토픽 설정
kafka:
  topics:
    file-process: file-process-topic
    file-result: file-result-topic